src/main/java/com/machiav3lli/backup/activities/BatchActivityX.java, src/main/java/com/machiav3lli/backup/activities/MainActivityX.java
when two concurrent threads were reinitializing list-member variable
=> Fixed: Race Condition in Main/Batch Activity 

src/main/java/com/machiav3lli/backup/handler/ShellCommands.java
Stupid mistake of mine. Sorry about that
=> Fixed: Wrong parameter usage when building array of apks to backup

src/main/res/raw-et/help.html, src/main/res/values-et/strings.xml, src/main/res/values/languagecodes.xml
Translated the app and help material to Estonian. Uncompiled and therefore untested, but I think I escaped all necessary characters.
=> Estonian translation

app/src/main/res/values/strings.xml
=> Erroneous app strings fixed

app/src/main/java/com/machiav3lli/backup/handler/SortFilterManager.java, app/src/main/java/com/machiav3lli/backup/items/SortFilterModel.java, app/src/main/res/layout/sheet_sort_filter.xml
I think, normal users will probably want labels at first (at least before they become comfortable with the ui).
It's also what I expect if labels have bigger titles.
=> sort by Label as default

app/src/main/java/com/machiav3lli/backup/Constants.java, app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.java, app/src/main/java/com/machiav3lli/backup/handler/action/BackupAppAction.java, app/src/main/java/com/machiav3lli/backup/items/AppInfoX.java, app/src/main/res/values/arrays.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_service.xml
Fixed: Backup is added to the backup history by the BackupAppAction to make sure, it's consistent and does not need to wait for the refresh from the UI
=> Added: configurable option to define when backup housekeeping shall happen

app/src/main/res/layout/item_batch_x.xml, app/src/main/res/layout/item_main_x.xml
I rearranged the update icon to the leftmost position.
At least it should not be hidden between other tags...
may be it could have a little distance (half step), to be more prominent.
=> position update tag leftmost

app/src/main/res/drawable/ic_special_24.xml, app/src/main/res/drawable/ic_update_24.xml
make this similar to the other (tag) icons, so colors.xml defines all these colors.
not sure why ?colorAccent etc. are used here...
maybe because of visual editing with the IDE
=> use colors.xml definitions for ic_special/ic_update

app/src/main/java/com/machiav3lli/backup/dialogs/BlacklistDialogFragment.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.kt, app/src/main/java/com/machiav3lli/backup/handler/SortFilterManager.kt, app/src/main/java/com/machiav3lli/backup/schedules/CustomPackageList.kt
fix all kinds of app list sorting...(hopefully)
* sortedWith for a collection isn't in place, see
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/sorted-with.html
* fix other occurances of sortedWith
* change oneliner to multiline for better debugging and better overview
* use label for custom list (solves #200)
* make sorting of blacklist and customlist similar
**Please check** if getting the context for customlist is correct
=> fix applist sorting

app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt
* ensure the loop continues on (even unexpected) exceptions
* ensure overall results in case of exceptions
* ensure the wakelock is released on exceptions (also in the first loop)
The diff looks much bigger than it is because of indentation changes, please compare the resulting file
=> catch inside loop and around

app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/fragments/SortFilterSheet.kt, app/src/main/java/com/machiav3lli/backup/handler/BackendController.kt, app/src/main/java/com/machiav3lli/backup/handler/DocumentContractApi.kt, app/src/main/java/com/machiav3lli/backup/items/AppInfoX.kt, app/src/main/java/com/machiav3lli/backup/items/BackupItem.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt
* uninstalled are now shown
* manually refresh rereads storage
* changing filters only changes view
* special backups should be shown
(not sure but I think they were missing in some situations)
* show empty list if everything filtered out
(don't replace by full list)
* try to catch more exceptions (questionable)
=> Pr fix empty+refresh+showuninstalled+catchall

README.md
=> Spelling (Affero) and link correction (txt -> md)

FAQ.md
Guess what, fixed stupid thing I did
=> First answer reorgainised

app/src/main/java/com/machiav3lli/backup/Constants.kt, app/src/main/java/com/machiav3lli/backup/items/SortFilterModel.kt, app/src/main/java/com/machiav3lli/backup/utils/FilterUtils.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/sheet_sort_filter.xml, app/src/main/res/values/strings.xml
Adding backup date sort option to address #377 
I'm not sure what to do about adding strings translations so it's just a default value for the additional button for now.
Also changed the text for the "Update All" button as it is confusing what the purpose of it is: update the apps or update the backups?
=> Add sort option for Backup Date

app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt
fixes #390
The mode is not set directly, but stored in a map and executed after all files are extracted.
This could be made more efficient (only less memory), by only postponing under certain conditions (a.k.a. write protected directory).
If desired, I would add another commit.
However: the memory consumption seems to be minor and the code is simpler (no condition checking, no duplication of chmod code etc.).
=> postpone chmod, fixes #390

app/src/main/java/com/machiav3lli/backup/fragments/BatchFragment.kt, app/src/main/java/com/machiav3lli/backup/fragments/HomeFragment.kt
showNow inside a thread seems to crash
=> fix crash on block list button

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/BackupSpecialAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreSystemAppAction.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/handler/BackupBuilder.kt, app/src/main/java/com/machiav3lli/backup/handler/NotificationHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/items/BackupProperties.kt, app/src/main/java/com/machiav3lli/backup/items/SpecialAppMetaInfo.kt, app/src/main/java/com/machiav3lli/backup/tasks/AppActionWork.kt, app/src/main/java/com/machiav3lli/backup/utils/DocumentUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/FileUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt, app/src/main/res/values-es/strings.xml
This is built on the existing PR #420. I used a different strategy to reduce the nullable objects consistently by throwing exceptions at an earlier point of time instead of using huge blocks with `let` or other scope functions.
=> Null pointer check elimiation

README.md
was lower case, should have been upper case
=> fixed changelog link

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt
create an interface of two functions:
genericBackupData(..., filesToBackup, ...)
genericBackupData(..., sourceDirectory, ...)
so they can later be implemented using external tar commands.
=> add genericBackupData(..., sourceDirectory, ...) as preparation for external tar

FAQ.md
A8-A11 goes to the text which says A12 is supported
=> Supported android update in FAQ

app/src/main/java/com/machiav3lli/backup/actions/RestoreSpecialAction.kt
ongoing work for special backups...
dl200010 on Matrix investigated this, and pushed me to add this, thanks!
The user/group/selinux context were wrong after restoring special backups.
Now, for each file, the attributes are saved and restored after replacing the file.
Next iteration will be an abstraction (save rights, restore rights or similar) and it should be merged in some way with `genericRestorePermissions`.
This comes to mind:
```
withSavedRights(file) [
do_some_thing_with(it)
}
```
Not sure how this would be done in the general case. I think of restoring rights for the directory with the same functionality and then use a kind of "apply rights of the directory to all files inside" for the data. This might be integrated into `withSavedRights` for a directory.
=> fix: special: remember permissions and set them after replacing the file

FAQ.md
Mainly replaced the occurrence of OABX/oabx/OAndBackupX with NB/nb/Neo-Backup.
Also replaced links in the FAQ to other stuff in the github repo (which included oanbbackupx).
=> Update regarding new project name - Neo-Backup

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/handler/BackendController.kt, app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/java/com/machiav3lli/backup/services/CommandReceiver.kt, app/src/main/java/com/machiav3lli/backup/utils/FileUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/AppSheetViewModel.kt
* don't throw away the complete cache all the time
* add conditions (as code blocks) for invalidated items to a list of filters
* checkCache uses these filters to remove items from the StorageFile cache
=> partial invalidateCache

app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/AppSheetViewModel.kt
* StorageFile create/delete add/remove to/from the cache directly
* also handles rename
* tested known backup first item / delete all backups
=> fix invalidateCache: first backup / delete all backups

FAQ.md
- little corrections + formating
- TB feature comparison as table
- added roadmap / Kanban for upcoming features link
- added notification details for schedules/batch 
- some adds for SMS/MMS + contacts
- added q&a for work profile / multi-user
=> FAQ - Update

app/src/main/java/com/machiav3lli/backup/OABX.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/handler/BackendController.kt, app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/services/PackageUnInstalledReceiver.kt, app/src/main/java/com/machiav3lli/backup/tasks/AppActionWork.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/BatchPackageItem.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/MainPackageItem.kt, app/src/main/java/com/machiav3lli/backup/utils/FileUtils.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/MainViewModel.kt, app/src/main/res/xml/preferences_advanced.xml
* fix invalidate...
* special packages still behave somehow "interesting"
* more settings to switch on or off certain details (to test differences in case of problems)
* some better defaults
* timer toast for updateBackupTable which is a bigger part than updateAppInfoTable
* some smaller things...
=> fix invalidate for packages: when backupdir changes or on un/install

FAQ.md
- added some device protected / device encrypted data details
- added link to Pizze's encryption tool
- added Harald's explanation from the chat regarding:
-- stop/pause/(un)suspend
-- SAF slowness details
=> Update FAQ.md - DES, link to encryption tool, stop/suspend, SAF details

FAQ.md
* added details for question(s) about the removal/disable the default (SAF) file manager
* slightly adjusted details about backing up contacts (right now under SMS & Call logs)
=> Update FAQ.md (SAF file manager, contacts)

app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt
should fix #550, may also fix #566
* genericRestorePermissions was canceled when all files are ignored, so the directory wasn't changed, but tarcmd needs this
* it is open / to be proved, if installing an apk changes the ignored directories to the new app user
* cache and also lib-main and similar have a group u0_aXXX_cache which happens to be the gid of XXX+20000, while u0_aXXX is XXX+10000. It would be possible to extract the XXX from the directory and only change the XXX for all files while keeping the offset (and also excluding all uids <10000). Though this would need to scan all files. To be faster it could be done in a script.
=> fix data reset after reboot (and update etc.) bug

app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt
StorageFile.size was missing the RootFile part
=> fix StorageFile.size for root shadow

app/src/androidTest/kotlin/research/Try_systemValues.kt, app/src/androidTest/kotlin/research/Try_trivia.kt, app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/utils/Dirty.kt
this is untested (time running out), but trivial, I think this will work (famous last words of the software developer :-))
=> chown cache directories to xxx_cache gid

FAQ.md
- new Qs+As for: -- use NB for device/ROM switch
-- can I backup NB settings
- start-time for schedules details
- other smaller updates  -- supported version
-- reboot NB for specials and ask for SMS privs
-- some links added
-- formatting
=> Update FAQ.md (ROM switch, NB settings bkp, ...)

FAQ.md
The wording was quite awkward and the language quite difficult to understand at times. Lack of articles made the whole FAQ a bit confusing. So I decided to rephrase them! And also there were a couple of typos. Also I have added a ton of `backticks` to the filenames to make them neater.
=> fixed typos and rephrased some stuff

app/build.gradle.kts, app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreSpecialAction.kt, app/src/main/java/com/machiav3lli/backup/dbs/entity/Backup.kt, app/src/main/java/com/machiav3lli/backup/preferences/ServicePreferences.kt, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt, app/src/main/res/values/strings.xml
This PR is intended to add the zstd compression related in [#444](https://github.com/NeoApplications/Neo-Backup/issues/444). With this compression, it is hoped that it can speed up the backup compression process
=> zstd compression support
