src/main/AndroidManifest.xml
Over 25% of the world's Android devices still run Android 6.0 or older [[1]](https://www.androidauthority.com/android-version-distribution-748439/). This version of Android still has native support for moving applications to SD cards — this is crucial when dealing with low-storage devices. Many more recent OEM OSes also support moving applications to SD cards. This means making applications movable to the SD card is IMHO a rational choice.
Add `android:installLocation="auto"` flag to AndroidMainfest.xml. The default for Android is, curiously, not `"auto"` but `"internalOnly"`
https://developer.android.com/guide/topics/data/install-location
Signed-off-by: Atrate <Atrate@protonmail.com>
=> Allow app to be moved to SD card

app/src/main/java/com/machiav3lli/backup/dialogs/BackupDialogFragment.java, app/src/main/java/com/machiav3lli/backup/dialogs/BatchConfirmDialog.java, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.java, app/src/main/java/com/machiav3lli/backup/handler/action/BackupAppAction.java, app/src/main/java/com/machiav3lli/backup/handler/action/RestoreAppAction.java, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.java, app/src/main/res/values/strings.xml
Users should be informed, that OABX is going to stop their apps and therefore also the services that would trigger alarms. Apps like alarm clocks or calendars are examples.
=> Added warning about stopped apps to the confirmation dialog

app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.java, app/src/main/java/com/machiav3lli/backup/dialogs/BlacklistDialogFragment.java, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.java, app/src/main/java/com/machiav3lli/backup/fragments/BatchFragment.java, app/src/main/java/com/machiav3lli/backup/fragments/MainFragment.java, app/src/main/java/com/machiav3lli/backup/fragments/PrefsFragment.java, app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.java, app/src/main/java/com/machiav3lli/backup/handler/SortFilterManager.java, app/src/main/java/com/machiav3lli/backup/handler/action/BackupAppAction.java, app/src/main/java/com/machiav3lli/backup/handler/action/RestoreAppAction.java, app/src/main/java/com/machiav3lli/backup/items/AppInfoX.java, app/src/main/java/com/machiav3lli/backup/items/BatchItemX.java, app/src/main/java/com/machiav3lli/backup/schedules/CustomPackageList.java, app/src/main/java/com/machiav3lli/backup/schedules/HandleScheduledBackups.java, app/src/main/java/com/machiav3lli/backup/tasks/BaseTask.java, app/src/main/java/com/machiav3lli/backup/utils/ItemUtils.java
for me the main purpose for AppInfoX is the abstraction of an entry in the list of "apps".
From my experience it should abstract the usage from outside.
From outside there should not be indirections like via getAppInfo() to determine basic attributes.
The field metainfo is an implementation detail and only exists, because it groups data for parceling.
The user of AppInfoX should not know internal details (from his POV), e.g. if the label is stored in metainfo and the name is not or even why there are two fields for the package name (in AppInfoX and metainfo) should not be visible.
The decisions like isDisabled or isSystem should be implemented at the same level, and in the object that is responsible.
As I understand it, metainfo is only a kind of a data structure for parceling or may be …
=> AppInfoX: make Abstraction more complete, mostly eliminate use of getAppInfo()

app/src/main/java/com/machiav3lli/backup/Constants.java, app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.java, app/src/main/java/com/machiav3lli/backup/items/AppInfoX.java, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences.xml
Small feature, that adds a new option to configure the amount of (valid) backup revisions to keep. The Default value is 2. Cleanup happens _after_ the backup is done. It doesn't matter if the backup was successful or failed. It would just truncate the number of backups to the wanted maximum.
=> Added: Housekeeping functionality for backup revisions

app/src/main/java/com/machiav3lli/backup/handler/action/BackupAppAction.java, app/src/main/java/com/machiav3lli/backup/handler/action/BackupSpecialAction.java, app/src/main/java/com/machiav3lli/backup/handler/action/BaseAppAction.java, app/src/main/java/com/machiav3lli/backup/handler/action/RestoreAppAction.java, app/src/main/java/com/machiav3lli/backup/handler/action/SystemRestoreAppAction.java
Killing an app before it's backup runs is a measure to prevent writes to the data directories while saving the data.
But this has several disadvantages:
- it (severely) changes the state of the system (e.g. wallpaper is lost, keyboard back to default, alarm doesn't work, services are no more running)
- you cannot restore the old state, because you don't have the history
- rebooting would be possible to restart all the services and apps that should run all the time, but it still doesn't solve some of the problems (e.g. most visible selection of a default keyboard and changed wallpaper)
- if an app is killed, there might be mechanisms to run it again immediately and this creates even more storage activity
Instead this PR implements pausing the processes belonging to each app by using the …
=> use STOP/CONT signals instead of killing the app, killPackage -> preprocess/postprocessPackage

app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.java
This implements feature request #188 by skipping the profile selection dialog if there is only one profile available.
=> Skip profile selection if there is only one profile

app/src/main/java/com/machiav3lli/backup/handler/DocumentContractApi.kt, app/src/main/java/com/machiav3lli/backup/items/AppInfoX.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt
the cache must be cleared if it is dirty (the cache.clear() in StorageFile)
the other changes are cosmetic, which I changed while trying to understand the code.
Mainly "fighting" Spaghetti code and "wrong" indentation (is this created by Kotlin converter?).
May be discussed.
At least
```
fun ... if ....
...
else
...
```
is very strange.
I also don't like
```
if ... try {
} catch {
}
```
`fun` does not pair with `else` and `catch` does not pair with `if`...I read these pairs as errors in structure...
I hope we agree on those
=> StorageFile cache: fix missing clear

app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt
A simple solution to something I wanted to change for some time.
The app list is only reread from "disk" if "something" changes, which we already try to maintain in cacheDirty.
I think this should be the same logic, so lets use the same flag.
May be there are better ways, but this was so simple, that I couldn't resist.
So far it seems to work (try my latest apk on Telegram)
There is one weird effect.
If I set the filter to "Apps without backup" I get a list with apps "without backups".
No pun intended!
This means, after a full backup, this list should be empty, but it is full and each app is missing the backups.
I know, the empty list is switched to the full list, but there must be something wrong with it.
Will have a look...
=> only get apps list if empty or storage cache is dirty

app/src/main/java/com/machiav3lli/backup/handler/action/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt
* don't use the **use** clause here, because it closes the inner stream
* the other one is tricky:
```
var tarEntry: TarArchiveEntry
while (archive.nextTarEntry.also { tarEntry = it } != null) {
```
the compiler is clever and detects that `tarEntry` is always initialized. But it is dumb, because it doesn't detect that `archive.nextTarEntry` (Java) can be `null` (at the end, though it's not explicitly Nullable). In this case it throws an exception.
This is my first try to solve that without changing too much:
```
var tarEntry: TarArchiveEntry? = null
while (archive.nextTarEntry.also { tarEntry = it } != null) {
val tarEntry = tarEntry!!
```
The tarEntry is now Nullable, but because there are many occurances in the loop it's assigned to the same name again, while checking if it's `null`.
* …
=> fix restore: openArchiveFile, uncompressTo

app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.kt, app/src/main/java/com/machiav3lli/backup/handler/action/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/items/AppInfo.kt, app/src/main/java/com/machiav3lli/backup/items/SpecialAppMetaInfo.kt
two fixes in one PR because they have dependent changes
* fixes crashes in some situations for special packages (e.g. delete all backups in app sheet)
* fixes housekeeping of backup revisions
* BEFORE didn't work and therefore could not use 1 revision
* special backups conflicted with another fix
(the special package definitions were always recreated by getSpecialPackages, so ad hoc changes did not work)
=> fix missing appinfo for special and housekeeping

app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/action/BackupSpecialAction.kt, app/src/main/java/com/machiav3lli/backup/utils/DocumentUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/FileUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt
mtime **IS** important for some purposes. Though I didn't see any effect up to now (but I don't restore!), I am quite sure that mtimes are used by usual software. It only might be a special Android thingy to ignore it, but for backups I would try to stay on the safe side.
if that matters, TiB and Swift restore the mtimes...
I push this early, before I have even started the restore part, because users are already creating backups with wrong mtimes.
=> add mtime to backups (restore still WIP)

app/src/main/java/com/machiav3lli/backup/handler/DocumentContractApi.kt
I once changed isPropertyFile to test the uri(!) for ".properties", which is wrong (but worked for local storage).
The uris for nextcloud (and probably others) only contain meaningless numbers.
=> fix: missing backups on nextcloud (and similar)

app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt
Fixes #213.
TL;DR: It reads the SELinux context from the directory and applies it recursively to the app data.
First I have looked into how Android implements SELinux. Besides the normal users, roles and types it uses Multi-Category Security (MCS). So an app data context might be `u:object_r:app_data_file:s0:c87,c257,c512,c768 `. 
The `u:object_r:app_data_file` is always the same and already correct, so we can ignore that. `s0` is also constant (sensitivity level 0) and correct. 
The problem after a data restore lies in the categories. It usually has 4 categories (range c0 - c1023) in 2 pairs. `c512,c768` is always there for apps, but the other pair changes:
> Android devices use dynamically generated MCS categories so that an app running on behalf of one user cannot read or write files …
=> Apply correct SELinux context after data restore

app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/test/java/ShellHandlerTest.kt
The regex `\s+` matches one or more spaces directly, so there are no empty tokens generated.
Additional filtering and error prone recombining is therefore not necessary anymore.
This makes the code simpler and also more reliable in my testing. 
Fixes #288.
Also I have added adjusted/extended ShellHandler tests, based on #291 from @hg42.
=>  Use split with regex for ls output 

app/src/main/java/com/machiav3lli/backup/utils/DocumentUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt
don't throw exceptions on these special files, because they stop the loop
* sockets need not to be backed up, they are automatically created and removed -> ignore
* char and block devices should not occur (says the former comment),
I think, they could eventually be backed up and restored, but this seems to be unnecessary -> later?
if those devices occur, we should eventually add an error to the action, but it's unclear how to propagate them to the ui level
=> fix: don't throw exceptions on some special files to be backed up (socket...)

app/src/main/java/com/machiav3lli/backup/actions/BackupSpecialAction.kt
e.g. special.wallpaper
```
"$userDir/wallpaper",
"$userDir/wallpaper_info.xml"
```
if $userDir/wallpaper does not exist, the other file isn't backed up.
EDIT: removed:
> I'm not happy with checking the error message. This may be dependend on the language and the message may change in the future.
> However it needs root, so we cannot check via an API (unless we can use root permissions for APIs, e.g. via Shizuku).
> It's not very likely to get other exceptions from suGetDetailedDirectoryContents, so we might remove the check.
DONE: removed the check
=> fix: missing files in special.* breaking the rest of the package

app/src/androidTest/java/SELinuxTest.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt
this fixes reports, that the selinux contexts are not restored.
The selinux patch from Jakeler doesn't seem to work in all cases.
There are cases where stat returns a context of "?".
Actually, there seem to be more systems where restorecon gives the correct result, while on the other hand stat doesn't work.
EDIT: it's the result for an unknown format character: "%C"
In this case we don't know the context of the directory and thus cannot set the context of the including files.
Before this patch, the context would not be set.
The patch adds a fall back to the former solution using restorecon, which usually also copies the context from the directory to it's contents (but for Jakeler this didn't seem to work).
I also added -F (force) to restorecon, in case it matters.
PS: we could eventually …
=> fix selinux context via restorecon in case the context is reported as "?"

app/src/androidTest/java/optional/ShellOptionalTests.kt, app/src/androidTest/java/tests/ShellTests.kt
the purpose is mainly testing every character value by building file names from ranges of character values.
The quoting works so far.
One thing remains open for discussion:
character values from 128 to 160 (space + 128) all fail, they seem to be removed from the file name in some way.
I had no time to debug this.
I think, the part from 128 to 160 can be added at the time we find the solution for this.
=> more shell tests

app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt
take this example command line:
`settings put global verifier_verify_adb_installs 0 && cat "/data/local/tmp/com.instagram.android.base.apk" | pm install -t -r -S 41020696 ; "/system/bin/toybox" rm "/data/local/tmp/com.instagram.android.base.apk" && settings put global verifier_verify_adb_installs 1`
let's introduce short names to show the structure:
`verifier_0 && cat_apk | pm_install ; rm_apk && verifier_1`
this is equivalent (in bash syntax, not sure if the shell has braces):
```
verifier_0 && { cat_apk | pm_install }
rm_apk && verifier_1
```
so if `verifier_0` fails `pm_install` doesn't happen.
`rm_apk` is executed unconditionally (so the `rm` afterwards in the code isn't necessary and always fails).
But if `rm_apk` fails, `verifier_1` is not executed.
I changed `&&` to `;` at multiple …
=> fix conditional executions

app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt
solves issue #392
dirs, fifos, links etc. cannot be created in a non-existent directory, just like a simple file...so do it for all
additionally, it is better to handle the exception handling consistent for all file types (instead of none for a simple file)
=> TarUtils: check parent directory for all file types, consistent exception handling

app/src/main/java/com/machiav3lli/backup/tasks/BaseActionTask.kt
The progress bar is updated via runOnUiThread, which is called via the UiThreadSttement class.
UiThreadStatement seems to be defined only in a test runner class.
Not sure why it was used?
The docs say, runOnUiThread should be called on "the" activity.
So I tried that.
At least it works for me (with limited testing, there might be edge cases that I don't have a clue of).
=> remove dependency on test runner (UIThreadStatement)

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt
People often post screenshots of the error dialog in the Telegram group, but we only see the error message.
I've changed backup and restore method to contain the executed command(s) as well, so we can better understand, what's going on.
Not perfect and maybe unclear if there is too much text, but this should rarely be the case.
Here's a example how it looks, if I break the shell command intentionally.
=> More detailed ActionResult messages if ShellCommand failed

app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/handler/BackendController.kt
despite our package name is added to the exclude list, it is NOT excluded (at least) from a manual backup and it hangs.
So, to be safe, I added the package name to doNotStop.
=> own package is not ignored, so instead we need to doNotStop

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/BackupSpecialAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreSystemAppAction.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/handler/NotificationHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/items/BackupProperties.kt, app/src/main/java/com/machiav3lli/backup/tasks/AppActionWork.kt, app/src/main/java/com/machiav3lli/backup/utils/DocumentUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/FileUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/AppSheetViewModel.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/AppSheetViewModelFactory.kt, app/src/main/res/values-es/strings.xml
Java→Kotlin conversion added many xxx!! constructs, that throw NullPointerExceptions, which don't say much about why they happen (file not found? backup directory not existent? etc.).
This is the first part of reducing such `xxx!!` constructs.
Please review this thoroughly.
Would be nice if more developers involved with the original code could have an eye on it (e.g. @Tiefkuehlpizze).
For each occurrence, I tried to do formal transformations that keep the semantic, and do the right thing in other cases, but I don't have insights in all the decisions according to the code. May be, some things are intentionally.
You should probably look at the changes with a more capable visual diff program (like `meld` or `windiff`), that can show diffs inside a line or ignore whitespace changes, because …
=> eliminate xxx!! constructs, because they throw unspecified NullPointerExceptions

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt
This separates the exclusion of cache* and lib from the backup. Both were dependent on the backup cache setting, but only cache* should (as the name says).
It also removes the exclusion of the cache from wiping at restore.
I think the cache is invalid after a restore, so it should be wiped, right?
As I don't restore with OABX on my daily driver currently, and my other phones are used for other projects, I cannot test this.
But I think the functionallity of the patch is obvious.
=> separate excluded dirs and cache

app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt
the exclude mechanism of toybox tar matches simple words like "lib" as complete file name without path.
So, `./files/usr/lib/...` was also excluded.
I added `./` to the directories (only for tarcmd, tarapi matches only at the top level)
=> fix: tarcmd: excluded directories should only match at the top of the tree

app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt, app/src/main/res/xml/preferences_advanced.xml
this is mainly to increase compatibility with v7 backups.
Original v7 tarapi saved symlinks as hardlinks and restored each link as symlink.
v8 restores symlinks as symlinks and hardlinks as hardlinks (as it should be, ideally).
To be compatible to v7 backups, I added an option strictHardLinks that is disabled by default.
As a result extracting v7 backups is supported by default.
BUT:
v8 still handles obb and media as plain tar files (without compression), while v7 saved them by simply copying the file tree. Because this had some errors, I didn't add compatibility (no urgent need to fix those issues).
So, to restore v7 backups, obb and media must be disabled.
Instead obb and media fo v7 backups can simply be restored with the original v7 apk.
This PR also contains more search paths to …
=> strict hard links, more root shadow paths

app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/res/xml/preferences_advanced.xml
* "delete all backups" of a package didn't work (and also deleting the last backup) because in case of the last backup the whole package dir was removed and this used another way to delete it, which couldn't delete recursively
* the `logcat` command was missing the `-d`. Without this logcat works like tail (running infinitely). I swear it worked at some point :-) I got a new adb version, may be that changed the behavior (but only guessing)
* default for restoreAvoidTemporaryDirectory is false, because it's much faster with tarapi (and it's not used for tarcmd)
=> fix: deleteallbackups+uncaughtExceptions+restoreAvoidTemporaryCopy

app/src/androidTest/kotlin/tests/Test_BackupRestore.kt, app/src/androidTest/kotlin/tests/Test_selinux.kt, app/src/androidTest/kotlin/tests/Test_shell.kt, app/src/main/AndroidManifest.xml, app/src/main/java/com/machiav3lli/backup/OABX.kt, app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreSpecialAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/activities/SplashActivity.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/fragments/BatchFragment.kt, app/src/main/java/com/machiav3lli/backup/fragments/HomeFragment.kt, app/src/main/java/com/machiav3lli/backup/fragments/PrefsServiceFragment.kt, app/src/main/java/com/machiav3lli/backup/fragments/PrefsToolsFragment.kt, app/src/main/java/com/machiav3lli/backup/handler/AssetHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellCommands.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/WorkHandler.kt, app/src/main/java/com/machiav3lli/backup/items/RootFile.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/java/com/machiav3lli/backup/services/ScheduleService.kt, app/src/main/java/com/machiav3lli/backup/services/WorkReceiver.kt, app/src/main/java/com/machiav3lli/backup/tasks/AppActionWork.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_advanced.xml
* use app instead of activity for some globals, for some things like work manager or preferences, contexts go down to the app context anyways
* move such global things like ShellHandler inititalization to the app, because it is created first and an activity is not necessary
* add WorkHandler (move everything related to it, except showRunningNotification for now)
* add AssetHandler and init as early as possible
* fix: avoid which command to find utilBox, just test the version and use the name. Long term it should probably be found to fix the path which is more secure
* fix testing
* add cacheRootFileAttributes to test if limited attribute caching is useful at all (isDirectory is used quite often)
* fix hanging RootFile shadow. Some storage paths tend to hang (e.g. `*/self/*`, reasons are …
=> fix hanging rootfile, WorkHandler, AssetHandler, use app for globals and early init

app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/test/kotlin/tests/Test_ShellHandler.kt
fixes ls output with api 26 (missing -ll option = --full-time = no seconds and nanoseconds and no time zone)
using Regex is more robust anyway and more clear (direct relation between regex group names and variables instead of splitting and using tokens[i])
=> handle toybox ls without -ll generically using Regex

app/src/main/java/com/machiav3lli/backup/actions/BackupCallLogsJSONAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreCallLogsJSONAction.kt
Remove LAST_MODIFIED, because the dialer app automatically updates the cache fields and the LAST_MODIFIED. This was causing duplicate call log entries.
=> Fix Call Log JSON Restore Duplicates

app/src/main/java/com/machiav3lli/backup/items/BackupProperties.kt
it's generally more robust to allow default values, e.g. in case a null value will be omitted in future etc.
=> make all properties optional, which allows compatibility with older backups (e.g. when it was without media, or without iv)

app/build.gradle.kts, app/schemas/com.machiav3lli.backup.dbs.ODatabase/3.json, app/schemas/com.machiav3lli.backup.dbs.ODatabase/4.json, app/src/androidTest/kotlin/tests/Test_BackupRestore.kt, app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/dbs/entity/Backup.kt, app/src/main/java/com/machiav3lli/backup/handler/BackupBuilder.kt, app/src/main/java/com/machiav3lli/backup/handler/LogsHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/WorkHandler.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/BackupItem.kt, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt, app/src/main/res/xml/preferences_service.xml
Antonios, please choose a level you want to accept (rejected commits will the return later in another PR, after discussion):
* compression=0 -> uncompressed backup
* load compression type from properties, so backups can have mixed flags
* add backupVersionCode for later use (e.g. allow v8 to load v7 backups)
* because toybox has bugs, users can copy a fixed toybox to /data/local (we might provide a flashable zip if a fixed version exists, or take the working A10 toybox instead -> needs to be tested)
* fix: in case disableVerfication is enabled, Neo Backup ignored the return code of pm install (might be replaced by a script, some time in the future)
* add a system to check additional conditions to backup test
=> compression=0, compressionType, backupVersionCode, allow replacement toybox in /data/local, return code with disableVerification

app/src/androidTest/kotlin/tests/Test_BackupRestore.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreSpecialAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/dbs/entity/Backup.kt, app/src/main/java/com/machiav3lli/backup/fragments/LogsFragment.kt, app/src/main/java/com/machiav3lli/backup/handler/LogsHandler.kt, app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/BackupItem.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/BatchPackageItem.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/MainPackageItem.kt, app/src/main/java/com/machiav3lli/backup/utils/TarUtils.kt, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values/strings.xml
* adds compatibility to v7 backups (unfortunately I couldn't test much of them)
* please consider changing the version to 8.1 for upcoming releases, in case we also want to be compatible to v8 backups before alpha9, becasue those don't have the additional properties (however oldVersion also means tarapi, but this shouldn't be a problem, because it's compatible, and also fast enough for restore)
* several fixes
* added "gz" and "old" to BackupItem
* added number of  backups to list items
=> oldVersion compatibility, several fixes

NOTES.md, app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/fragments/HomeFragment.kt, app/src/main/java/com/machiav3lli/backup/handler/WorkHandler.kt, app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/items/StorageFile.kt, app/src/main/java/com/machiav3lli/backup/services/CommandReceiver.kt, app/src/main/java/com/machiav3lli/backup/services/PackageUnInstalledReceiver.kt, app/src/main/java/com/machiav3lli/backup/tasks/AppActionWork.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/AppSheetViewModel.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/MainViewModel.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/preferences_advanced.xml
* add useExpedited, fixes killing jobs after 10 minutes
* doWork is limited to 10 min at least in pre A12 (when JobScheduler is used internally)
* the only way to fix this for all cases seems to be using the setExpedited function (foreground is not enough)
* see the new NOTES.md
* add package name as tag to see it in logcat messages
* we only see the tags in logcat
* could also be used to select work
* getAppBackupRoot: make sure the context is always the app context
* for me it doesn't make sense to shuffle the context through all functions if all we want is the app context
* it also makes clear that the app context is used not some other context from "dubious" sources
* use big letters for abbreviations
* abbreviations are now shown as big letters, e.g. com.google.android -> C.G.A
* fix …
=> fix 10min limit, add packageName when calling HomePackageRecycler

app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt
* freezing on com.google.android.*
Some packages with the pattern `com.android.XXX` are excluded from STOP signals and pmSuspend or ignored completely.
This patch prevents the case when e.g. on the Android emulator and some GSIs and probably some Google devices, such packages are replaced by similar `com.google.android.XXX` packages, which are now excluded, too. I generally replaced a wildcard `com.android.XXX` by `*.android.XXX` to be on the safe side.
Like Google other vendors could also get the idea and use their own name in the package name and it could also be `org.*` or similar.
* ignore empty permissions (pm grant p.k.g "" = error)
This will help, when we get permissions with an empty name (not to confuse with an empty list, which is already handled).
Note, that this prevents an …
=> fix freezing on com.google.android.providers.* etc., ignore empty string permissions (pm grant p.k.g "" = error)

app/src/main/java/com/machiav3lli/backup/handler/BackendController.kt, app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/BatchPackageItem.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/MainPackageItem.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/MainViewModel.kt
* use ensureBackupList in all Package-Recyclers places to ensure backupList is loaded
* it's lean because only shown items are refreshed
* it ensures that a user always sees correct items
* AppSheet works from such an item, too
* ensure that a Package object for a packageName is always the same (cache)
=> add ensureBackupList to fix backupLists, also make Packages singletons by cache

app/src/main/java/com/machiav3lli/backup/OABX.kt, app/src/main/java/com/machiav3lli/backup/activities/IntroActivityX.kt, app/src/main/java/com/machiav3lli/backup/activities/PrefsActivity.kt, app/src/main/java/com/machiav3lli/backup/activities/SplashActivity.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/fragments/HelpSheet.kt, app/src/main/java/com/machiav3lli/backup/fragments/PrefsUserFragment.kt, app/src/main/java/com/machiav3lli/backup/handler/BackendController.kt, app/src/main/java/com/machiav3lli/backup/handler/BackupRestoreHelper.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/handler/WorkHandler.kt, app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/services/ScheduleService.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/Components.kt, app/src/main/java/com/machiav3lli/backup/ui/compose/item/TopBar.kt, app/src/main/java/com/machiav3lli/backup/utils/PrefUtils.kt, app/src/main/java/com/machiav3lli/backup/utils/UIUtils.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/AppSheetViewModel.kt, app/src/main/java/com/machiav3lli/backup/viewmodels/MainViewModel.kt, app/src/main/res/values/strings.xml
* Disable/Enable button changes instantly (updated from package manager)
* Launch button is disabled if app is disabled
* make refresh of backupList transactional (collect backups and set the complete list, less recomposes etc.)
also
* fixes missing version in HelpSheet
* fixes deleting old backups (old properties file name doesn't use nanoseconds)
* fixes crash instead of "root missing" message
=> fix AppSheet reactivity

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/actions/RestoreAppAction.kt, app/src/main/java/com/machiav3lli/backup/activities/MainActivityX.kt, app/src/main/java/com/machiav3lli/backup/fragments/AppSheet.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellCommands.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, app/src/main/java/com/machiav3lli/backup/items/Package.kt, app/src/main/java/com/machiav3lli/backup/tasks/BackupActionTask.kt, app/src/main/res/xml/preferences_advanced.xml
Scan a whole tree instead of one command for each directory.
This works nice, but doesn't help as much as I thought for tarapi speed.
Could eventually be used for tarcmd if we need more sophisticated file filtering.
Additionally it could make tarapi and tarcmd more compatible according to filtering.
Also, some smaller things...
=> use "find | xargs ls" to recursively scan a file tree

app/build.gradle.kts, app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt, build.gradle.kts
algorithm is tested, but needs prove for the version ranges:
* what is our first tested version? (0.8.0 for now)
* does 0.8.7 work? (installable as toybox-ext via Magisk module)
In the api32 emulator the installed toybox-ext isn't working for some reason. It looks like it cannot find it's own path. Starting `/system/xbin/toybox-ext` always gives an error about it's realpath.
Please report if you don't have this in the emulator (using Magisk and the toybox(ext) module).
=> select utilBox by score (version based for now, may be real tests later)

app/src/main/java/com/machiav3lli/backup/actions/BackupAppAction.kt, app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt
libsu tries three steps and takes the first that works:
* `su --mount-master`
* `su`
* `sh`
External commands (like tar) that cannot use the normal libsu shell functions (which collect output lines into an array) must add `--mount-master` by themselves.
**After this PR those commands only use `--mount-master` if libsu detected it before.**
Probably fixes #562, though it's still not clear if it would work without `--mount-master` functionality.
But at least it should then work like older OAndBackup* versions:
> Meanwhile the good-old oandbackup works.
`--mount-master` seems to be necessary for api30++, so it may work up to A10
> I now learned that su needs a --mount-master option on newer Android versions (API 30++).
> Otherwise the namespace of the OAndBackupX user id is totally different …
=> automatically adapt `--mount-master` option to what libsu detected

app/src/main/java/com/machiav3lli/backup/fragments/BatchFragment.kt
* batch backup/restore did not use the filtered (and searched) selection (no filterPredicate)
* the result were "could not backup apk" messages on deinstalled packages
* if only data was backed up, the backups were empty
=> fix deinstalled packages included in backup, also obey search

app/src/main/java/com/machiav3lli/backup/actions/BaseAppAction.kt
"Vanced microg" uses a package name com.mgoogle.android.gms that was matched by ignoredPackages.
The regex used patterns like .*.android.gms
Now it uses more explicit patterns like com.(google.)android.gms
=> fix too wide exclusion list (allow com.mgoogle.android.gms)

app/src/main/java/com/machiav3lli/backup/handler/ShellHandler.kt
In some roms(tested on Ricedroid 10.2) nsenter -t 1 -m sh gives the following error
ScriptException occurred on external_files backup: com.machiav3lli.backup.actions.BaseAppAction$ScriptException: nsenter: /proc/0/ns/mnt: No such file or directory - nsenter: /proc/0/ns/mnt: No such file or directory
Using nsenter --mount=/proc/1/ns/mnt sh should work in every cases.
=> Fix nsenter method of global mount namespace in some cases

FAQ.md
1) Make FAQ clearer in some places
2) Move "migrate system data" next to "restore system apps/data" in the comparison table, as they refer to the same sort of things
=> Small edits to FAQ.md
